# Site settings
title: Alva Fandrey
email: alva.fandrey@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Full Stack Developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  afandrey
screenshot: http://afandrey.github.io/files/images/screenshot.jpg

# Build settings
markdown: kramdown

collections:
  courses:
    output: true
  projects:
    output: true
